name: Docker Image CI

on:
  push:
    branches: [ "johny-facens" ]
  pull_request:
    branches: [ "johny-facens" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
    - name: Build with Maven
      run: ./mvnw clean install
    - name: Build the Docker image
      run: docker build  -f Dockerfile . -t webgoat/webgoat
