name: Docker Image CI

on:
  push:
    branches: [ "johny-facens" ]
  pull_request:
    branches: [ "johny-facens" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Build with Maven
      run: ./mvnw clean install
    - name: Build the Docker image
      run: docker build  -f Dockerfile . -t webgoat/webgoat
    - uses: docker/build-push-action@v2
      with:
        tags: webgoat/webgoat:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: webgoat/webgoat:latest
        run: docker run -d -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 webgoat/webgoat
