name: CICD

on:
  push:
    branches: johny-facens  # Execute em pushes para main e develop
  pull_request:
    branches: johny-facens  # Execute em pull requests para main e develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Necessário para o SonarCloud analisar todo o histórico do código

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build with Maven
      run: mvn -B verify

    - name: SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necessário para o SonarCloud
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token do SonarCloud
      run: mvn sonar:sonar -Dsonar.projectKey=johnyramos_WebGoat -Dsonar.organization=johnyramos -Dsonar.host.url=https://sonarcloud.io

    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      env:
        # actions/setup-java@v1 changes JAVA_HOME so it needs to be reset to match the depcheck image
        JAVA_HOME: /opt/jdk
      with:
        project: 'test'
        path: '.'
        format: 'HTML'
        out: 'reports' # this is the default, no need to specify unless you wish to override it
        args: >
          --enableRetired
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
         name: Depcheck report
         path: ${{github.workspace}}/reports
        
    - name: Start WebGoat
      run: mvn -pl webgoat-server spring-boot:start &> /dev/null & sleep 60



# Substitua com as suas informações:
# YOUR_SONAR_PROJECT_KEY
# YOUR_SONAR_ORGANIZATION


# Crie os seguintes secrets no seu repositório:
# SONAR_TOKEN (token do SonarCloud)
# ZAP_API_KEY (chave da API do ZAP - opcional, necessário apenas para recursos avançados)
